In [108]:
# Defining 2 2D arrays
arr1 = np.array([[0,1,2],[2,4,5]])
arr2 = np.array([[0,1,2],[2,4,5]])

# Multiplying the arrays and printing that
arr_multiplied = arr1 * arr2

print(arr_multiplied)


[[ 0  1  4]
 [ 4 16 25]]


In [103]:

import numpy as np

arr = np.ndarray(shape = (1,2), dtype=np.int8) 

arr[0] = 3

arr2 = np.array([1,2,4])

arr2[2] = 194

print(arr)
print(arr2)

[[3 3]]
[  1   2 194]
