In [3]:
import numpy as np

In [27]:
# Creating Arrays

# Array of zeros
zeros = np.zeros((2, 3))
print("Zeros Array:\n", zeros)

# Array of ones
ones = np.ones((3, 3))
print("Ones Array:\n", ones)

# Array with a range of numbers
range_arr = np.arange(0, 10, 2)  # Start, stop, step
print("Range Array:", range_arr)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Range Array: [0 2 4 6 8]


In [25]:
# Mathematical Operations
arr = np.array([10, 23, 3, 4])

# Add, multiply, and square elements
print("Add 5:", arr + 5)
print("Multiply by 2:", arr * 2)
print("Squared:", arr ** 2)

# Add two arrays
arr2 = np.array([5, 6, 7, 8])
print("Element-wise Addition:", arr + arr2)


Add 5: [15 28  8  9]
Multiply by 2: [20 46  6  8]
Squared: [100 529   9  16]
Element-wise Addition: [15 29 10 12]


In [21]:
# Random Number Generation

# Random floats between 0 and 1
rand_floats = np.random.random((2, 3))
print("Random Floats:\n", rand_floats)

# Random integers
rand_ints = np.random.randint(1, 50, (2, 4))  
print("Random Integers:\n", rand_ints)


Random Floats:
 [[0.17314291 0.87514857 0.40727328]
 [0.70841838 0.20420127 0.6557908 ]]
Random Integers:
 [[38 31 17 14]
 [43 27 37 15]]


In [19]:
# Array Indexing and Slicing

arr = np.array([[15, 11, 25], [19, 22, 31], [17, 56, 29]])

# Accessing a specific element
print("Element at row 1, col 2:", arr[1, 2])  # 30

# Slicing rows and columns
print("First column:", arr[:, 0])  # [5, 20, 35]
print("Subarray (last 2 rows, last 2 cols):\n", arr[1:, 1:])


Element at row 1, col 2: 31
First column: [15 19 17]
Subarray (last 2 rows, last 2 cols):
 [[22 31]
 [56 29]]


In [17]:
# Statistical Operations

arr = np.array([5, 10, 11, 45, 13, 46, 58])

# Calculate common statistics
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Standard Deviation:", np.std(arr))



Sum: 188
Mean: 26.857142857142858
Max: 58
Standard Deviation: 20.251480167622113


In [29]:
# Reshaping Arrays

import numpy as np

# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping into a 2x3 array
reshaped = arr.reshape((2, 3))
print("Reshaped to 2x3:\n", reshaped)

# Reshaping into a 3x2 array
reshaped_2 = arr.reshape((3, 2))
print("Reshaped to 3x2:\n", reshaped_2)


Reshaped to 2x3:
 [[1 2 3]
 [4 5 6]]
Reshaped to 3x2:
 [[1 2]
 [3 4]
 [5 6]]
